version: "3.9"
services:
  nginx:
    container_name: jump24-nginx
    image: nginx:latest
    restart: unless-stopped
    volumes:
      - ./docker/nginx/site.conf:/etc/nginx/conf.d/site.conf
      - ./webroot:/var/www/webroot
    ports:
      - "8000:80"
      - "8443:443"
    working_dir: /var/www/webroot
    networks:
      - jump24-network
    depends_on:
      - php
  php:
    container_name: jump24-php
    build:
      dockerfile: ./docker/php/Dockerfile
      context: ./
    restart: unless-stopped
    volumes:
      - ./:/var/www
    working_dir: /var/www
    networks:
      - jump24-network
    depends_on:
      - mysql
  mysql:
    container_name: jump24-mysql
    image: mysql:8.0
    restart: unless-stopped
    volumes:
      - mysql-data:/var/lib/mysql
    environment:
      MYSQL_ROOT_PASSWORD: "secret"
      MYSQL_DATABASE: "my_app"
      MYSQL_USER: "secret"
      MYSQL_PASSWORD: "my_app"
    networks:
      - jump24-network
volumes:
  mysql-data:
    driver: local
networks:
  jump24-network:
    driver: bridge
